# Generated by Django 3.1.7 on 2021-05-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_piece', models.CharField(max_length=200, null=True)),
                ('quntite_piece', models.IntegerField(default=1, null=True)),
                ('fabricant', models.CharField(max_length=200, null=True)),
                ('reference_fabricant', models.CharField(max_length=200, null=True)),
                ('fournisseur', models.CharField(max_length=200, null=True)),
                ('reference_fournisseur', models.CharField(max_length=200, null=True)),
                ('etat', models.CharField(choices=[('Validée', 'Validée'), ('Non Validée', 'Non Validée')], max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, null=True)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Electrique', 'Electrique'), ('Mechanique', 'Mechanique')], max_length=200, null=True)),
                ('prix', models.FloatField(default=0.0, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
