# Generated by Django 3.1.7 on 2021-05-02 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_demande_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.piece'),
        ),
        migrations.AddField(
            model_name='demande',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.projet'),
        ),
    ]
