# Generated by Django 3.1.7 on 2021-05-02 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_fabricant_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabricant',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='fabricant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='fabricant',
            name='telephone',
        ),
    ]
