# Generated by Django 3.1.7 on 2021-05-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210503_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='categorie',
            field=models.CharField(choices=[('Electrique', 'Electrique'), ('Mecanique', 'Mecanique')], max_length=200, null=True),
        ),
    ]
