# Generated by Django 3.1.7 on 2021-05-02 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210503_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='fabricant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fabricant'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fournisseur'),
        ),
    ]
