# Generated by Django 3.1.7 on 2021-05-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210503_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='durée_semaines',
            new_name='durée_en_semaines',
        ),
    ]
