# Generated by Django 3.1.7 on 2021-05-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210517_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employé',
            old_name='user',
            new_name='username',
        ),
    ]
