# Generated by Django 3.1.7 on 2021-05-18 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210517_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='pieces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.piece'),
        ),
    ]
