# Generated by Django 3.1.7 on 2021-05-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210519_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='commentaire',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='statut',
            field=models.CharField(blank=True, choices=[('Validée', 'Validée'), ('Non Validée', 'Non Validée')], max_length=200, null=True),
        ),
    ]
