# Generated by Django 3.1.7 on 2021-05-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210502_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='commentaire',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
