# Generated by Django 3.1.7 on 2021-05-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_demande_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('telephone', models.PositiveIntegerField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('telephone', models.PositiveIntegerField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('pieces', models.ManyToManyField(to='accounts.Piece')),
            ],
        ),
    ]
