# Generated by Django 3.1.7 on 2021-05-03 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210503_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='quntite_piece',
            new_name='quantite_piece',
        ),
        migrations.AddField(
            model_name='piece',
            name='fabricant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fabricant'),
        ),
    ]
