# Generated by Django 3.1.7 on 2021-05-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210503_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='etat',
            new_name='statut',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='etat',
            new_name='statut',
        ),
    ]
