# Generated by Django 3.1.7 on 2021-05-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210504_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employé',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('telephone', models.PositiveIntegerField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('adresse', models.CharField(max_length=200, null=True)),
                ('titre', models.CharField(max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.session')),
            ],
        ),
        migrations.CreateModel(
            name='Demande_Validée',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_validation', models.DateTimeField(auto_now_add=True, null=True)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande')),
                ('validateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employé')),
            ],
        ),
        migrations.CreateModel(
            name='Demande_Non_Validée',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rejection', models.DateTimeField(auto_now_add=True, null=True)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande')),
                ('rejeteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employé')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_livraison', models.DateField()),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande_validée')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fournisseur')),
            ],
        ),
    ]
