# Generated by Django 3.1.7 on 2021-05-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210517_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employé',
            old_name='username',
            new_name='session_user',
        ),
    ]
