# Generated by Django 3.1.7 on 2021-05-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210517_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('Livrée', 'Livrée'), ('En cours', 'En cours'), ('En retard', 'En retard'), ('Annulée', 'Annulée')], max_length=200, null=True),
        ),
    ]
