# Generated by Django 3.1.7 on 2021-05-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_commande_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='pieces',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='pieces',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.piece'),
        ),
    ]
