# Generated by Django 3.1.7 on 2021-05-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210518_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.demande'),
        ),
    ]
